# Generated by Django 3.1.3 on 2021-03-16 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDeliverer',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('full_name', models.CharField(blank=True, help_text='Họ và tên', max_length=300, null=True)),
                ('code', models.CharField(blank=True, help_text='Code', max_length=30, null=True)),
                ('department', models.CharField(blank=True, help_text='Phòng ban', max_length=300, null=True)),
                ('email', models.CharField(blank=True, help_text='Email', max_length=300, null=True)),
                ('telephone', models.CharField(blank=True, help_text='Điện thoại', max_length=300, null=True)),
                ('cre_date', models.DateTimeField(auto_now=True, help_text='Ngày tạo')),
                ('upd_date', models.DateTimeField(auto_now=True, help_text='Ngày cập nhật')),
            ],
            options={
                'db_table': 'ContractDeliverer',
                'ordering': ['cre_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('contract_number', models.CharField(blank=True, help_text='Số hợp đồng', max_length=300, null=True)),
                ('client_name', models.CharField(blank=True, help_text='Tên khách hàng', max_length=300, null=True)),
                ('customer_id', models.CharField(blank=True, help_text='Số CMND khách hàng', max_length=300, null=True)),
                ('plate_number', models.CharField(blank=True, help_text='Biển số xe', max_length=300, null=True)),
                ('other_doc', models.CharField(blank=True, help_text='Chứng từ khác', max_length=10, null=True)),
                ('mrc', models.BooleanField(help_text='Chứng từ MRC')),
                ('notes', models.CharField(blank=True, help_text='Ghi chú', max_length=300, null=True)),
                ('cre_date', models.DateTimeField(auto_now=True)),
                ('upd_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Contract_Description',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotorbikeRegisCert',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('province_public_security', models.CharField(blank=True, help_text='Công an tỉnh', max_length=300, null=True)),
                ('district_public_security', models.CharField(blank=True, help_text='Công an huyện', max_length=300, null=True)),
                ('number', models.CharField(blank=True, help_text='Số giấy chứng nhận', max_length=8, null=True)),
                ('owner', models.CharField(blank=True, help_text='Tên chủ xe', max_length=300, null=True)),
                ('address', models.CharField(blank=True, help_text='Địa chỉ', max_length=300, null=True)),
                ('brand', models.CharField(blank=True, help_text='Nhãn hiệu', max_length=300, null=True)),
                ('model_code', models.CharField(blank=True, help_text='Số loại', max_length=300, null=True)),
                ('engine', models.CharField(blank=True, help_text='Số máy', max_length=300, null=True)),
                ('chassis', models.CharField(blank=True, help_text='Số khung', max_length=300, null=True)),
                ('color', models.CharField(blank=True, help_text='Màu', max_length=20, null=True)),
                ('activation_scope', models.CharField(blank=True, help_text='Phạm vi hoạt động', max_length=300, null=True)),
                ('plate', models.CharField(blank=True, help_text='Biển số đăng ký', max_length=50, null=True)),
                ('date_of_expiry', models.DateField(help_text='Giá trị đến ngày')),
                ('cre_date', models.DateTimeField(auto_now=True, help_text='Ngày tạo')),
                ('upd_date', models.DateTimeField(auto_now=True, help_text='Ngày cập nhật')),
            ],
            options={
                'db_table': 'Motorbike_Registration_Certificate',
                'ordering': ['cre_date'],
            },
        ),
        migrations.AddIndex(
            model_name='motorbikeregiscert',
            index=models.Index(fields=['id'], name='Motorbike_R_id_8c137e_idx'),
        ),
        migrations.AddIndex(
            model_name='motorbikeregiscert',
            index=models.Index(fields=['owner'], name='Motorbike_R_owner_44a0f2_idx'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cert',
            field=models.OneToOneField(help_text='Chứng nhận đăng kí xe mô tô, gắn máy', on_delete=django.db.models.deletion.CASCADE, to='backend.motorbikeregiscert'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contract_deliverer',
            field=models.OneToOneField(help_text='Thông tin người giao', on_delete=django.db.models.deletion.CASCADE, to='backend.contractdeliverer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contract_desc',
            field=models.OneToOneField(help_text='Mô tả', on_delete=django.db.models.deletion.CASCADE, to='backend.contractdesc'),
        ),
        migrations.AddField(
            model_name='contractdesc',
            name='contract_id',
            field=models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.CASCADE, related_name='desc', to='backend.contractdeliverer'),
        ),
        migrations.AddIndex(
            model_name='contractdeliverer',
            index=models.Index(fields=['id'], name='ContractDel_id_38ebde_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdeliverer',
            index=models.Index(fields=['full_name'], name='ContractDel_full_na_ff3495_idx'),
        ),
    ]
