# Generated by Django 3.1.3 on 2021-03-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210316_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractdeliverer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contractdesc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='motorbikeregiscert',
            options={},
        ),
    ]
