# Generated by Django 3.1.3 on 2021-03-16 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210316_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationBack',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('owner', models.CharField(blank=True, default=7821139534, help_text='Tên chủ xe', max_length=300, null=True)),
                ('address', models.CharField(blank=True, default=7767455483, help_text='Địa chỉ', max_length=300, null=True)),
                ('brand', models.CharField(blank=True, default=745542049, help_text='Nhãn hiệu', max_length=300, null=True)),
                ('model_code', models.CharField(blank=True, default=2340933738, help_text='Số loại', max_length=300, null=True)),
                ('engine', models.CharField(blank=True, default=1740233534, help_text='Số máy', max_length=300, null=True)),
                ('chassis', models.CharField(blank=True, default=8418541317, help_text='Số khung', max_length=300, null=True)),
                ('color', models.CharField(blank=True, default=4436099392, help_text='Màu', max_length=20, null=True)),
                ('activation_scope', models.CharField(blank=True, default=2166614763, help_text='Phạm vi hoạt động', max_length=300, null=True)),
                ('plate', models.CharField(blank=True, default=3174418572, help_text='Biển số đăng ký', max_length=50, null=True)),
                ('date_of_expiry', models.DateField(default=293781651, help_text='Giá trị đến ngày')),
                ('cre_date', models.DateTimeField(auto_now=True, help_text='Ngày tạo')),
                ('upd_date', models.DateTimeField(auto_now=True, help_text='Ngày cập nhật')),
            ],
            options={
                'ordering': ['cre_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificationFront',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('province_public_security', models.CharField(blank=True, default=45211182, help_text='Công an tỉnh', max_length=300, null=True)),
                ('district_public_security', models.CharField(blank=True, default=6056040471, help_text='Công an huyện', max_length=300, null=True)),
                ('number', models.CharField(blank=True, default=6720636675, help_text='Số giấy chứng nhận', max_length=8, null=True)),
                ('cre_date', models.DateTimeField(auto_now=True, help_text='Ngày tạo')),
                ('upd_date', models.DateTimeField(auto_now=True, help_text='Ngày cập nhật')),
            ],
            options={
                'ordering': ['cre_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='contractdeliverer',
            options={'ordering': ['cre_date']},
        ),
        migrations.AlterModelOptions(
            name='contractdesc',
            options={'ordering': ['cre_date']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['cre_date']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cert',
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='code',
            field=models.CharField(blank=True, default=2620803299, help_text='Code', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='department',
            field=models.CharField(blank=True, default=78490139, help_text='Phòng ban', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='email',
            field=models.CharField(blank=True, default=2558498519, help_text='Email', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='full_name',
            field=models.CharField(blank=True, default=9251101756, help_text='Họ và tên', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='telephone',
            field=models.CharField(blank=True, default=3548416206, help_text='Điện thoại', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='client_name',
            field=models.CharField(blank=True, default=7426829962, help_text='Tên khách hàng', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='contract_number',
            field=models.CharField(blank=True, default=8625629488, help_text='Số hợp đồng', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='customer_id',
            field=models.CharField(blank=True, default=4306277547, help_text='Số CMND khách hàng', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='notes',
            field=models.CharField(blank=True, default=784263883, help_text='Ghi chú', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='other_doc',
            field=models.CharField(blank=True, default=7562585921, help_text='Chứng từ khác', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='plate_number',
            field=models.CharField(blank=True, default=4458966, help_text='Biển số xe', max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='MotorbikeRegisCert',
        ),
        migrations.AddField(
            model_name='customer',
            name='cert_back',
            field=models.OneToOneField(blank=True, help_text='Mặt sau chứng nhận đăng kí xe mô tô, gắn máy', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.certificationback'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cert_front',
            field=models.OneToOneField(blank=True, help_text='Mặt trước chứng nhận đăng kí xe mô tô, gắn máy', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.certificationfront'),
        ),
    ]
