# Generated by Django 3.1.3 on 2021-03-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210316_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationback',
            name='activation_scope',
            field=models.CharField(blank=True, default=2800707226, help_text='Phạm vi hoạt động', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='address',
            field=models.CharField(blank=True, default=1398831982, help_text='Địa chỉ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='brand',
            field=models.CharField(blank=True, default=7512753680, help_text='Nhãn hiệu', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='chassis',
            field=models.CharField(blank=True, default=1982861182, help_text='Số khung', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='color',
            field=models.CharField(blank=True, default=2398376013, help_text='Màu', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='date_of_expiry',
            field=models.DateField(default=7248801088, help_text='Giá trị đến ngày'),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='engine',
            field=models.CharField(blank=True, default=4898240052, help_text='Số máy', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='model_code',
            field=models.CharField(blank=True, default=6019141298, help_text='Số loại', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='owner',
            field=models.CharField(blank=True, default=6715270457, help_text='Tên chủ xe', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='plate',
            field=models.CharField(blank=True, default=2172296359, help_text='Biển số đăng ký', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificationfront',
            name='district_public_security',
            field=models.CharField(blank=True, default=598165671, help_text='Công an huyện', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationfront',
            name='number',
            field=models.CharField(blank=True, default=1459738381, help_text='Số giấy chứng nhận', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='certificationfront',
            name='province_public_security',
            field=models.CharField(blank=True, default=8223171782, help_text='Công an tỉnh', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='code',
            field=models.CharField(blank=True, default=3833507414, help_text='Code', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='department',
            field=models.CharField(blank=True, default=1713478709, help_text='Phòng ban', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='email',
            field=models.CharField(blank=True, default=7604291626, help_text='Email', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='full_name',
            field=models.CharField(blank=True, default=6227985741, help_text='Họ và tên', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='telephone',
            field=models.CharField(blank=True, default=9369668609, help_text='Điện thoại', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='client_name',
            field=models.CharField(blank=True, default=3359542162, help_text='Tên khách hàng', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='contract_number',
            field=models.CharField(blank=True, default=9940892381, help_text='Số hợp đồng', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='customer_id',
            field=models.CharField(blank=True, default=1819164633, help_text='Số CMND khách hàng', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='notes',
            field=models.CharField(blank=True, default=580684776, help_text='Ghi chú', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='other_doc',
            field=models.CharField(blank=True, default=5013496709, help_text='Chứng từ khác', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='plate_number',
            field=models.CharField(blank=True, default=3191372715, help_text='Biển số xe', max_length=300, null=True),
        ),
    ]
