# Generated by Django 3.1.3 on 2021-03-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210316_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationback',
            name='activation_scope',
            field=models.CharField(blank=True, default=9729492172, help_text='Phạm vi hoạt động', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='address',
            field=models.CharField(blank=True, default=3591315196, help_text='Địa chỉ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='brand',
            field=models.CharField(blank=True, default=7464673328, help_text='Nhãn hiệu', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='chassis',
            field=models.CharField(blank=True, default=837617816, help_text='Số khung', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='color',
            field=models.CharField(blank=True, default=4425626478, help_text='Màu', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='date_of_expiry',
            field=models.DateField(default=6913462097, help_text='Giá trị đến ngày'),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='engine',
            field=models.CharField(blank=True, default=3110628251, help_text='Số máy', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='model_code',
            field=models.CharField(blank=True, default=7147326862, help_text='Số loại', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='owner',
            field=models.CharField(blank=True, default=6130364724, help_text='Tên chủ xe', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationback',
            name='plate',
            field=models.CharField(blank=True, default=6367103494, help_text='Biển số đăng ký', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificationfront',
            name='district_public_security',
            field=models.CharField(blank=True, default=5327227885, help_text='Công an huyện', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificationfront',
            name='number',
            field=models.CharField(blank=True, default=121122830, help_text='Số giấy chứng nhận', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='certificationfront',
            name='province_public_security',
            field=models.CharField(blank=True, default=6632921850, help_text='Công an tỉnh', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='code',
            field=models.CharField(blank=True, default=9767575259, help_text='Code', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='department',
            field=models.CharField(blank=True, default=1686176104, help_text='Phòng ban', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='email',
            field=models.CharField(blank=True, default=9807707425, help_text='Email', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='full_name',
            field=models.CharField(blank=True, default=9698492701, help_text='Họ và tên', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdeliverer',
            name='telephone',
            field=models.CharField(blank=True, default=4675477702, help_text='Điện thoại', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='client_name',
            field=models.CharField(blank=True, default=9733586045, help_text='Tên khách hàng', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='contract_number',
            field=models.CharField(blank=True, default=483574227, help_text='Số hợp đồng', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='customer_id',
            field=models.CharField(blank=True, default=4826374634, help_text='Số CMND khách hàng', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='notes',
            field=models.CharField(blank=True, default=5689602174, help_text='Ghi chú', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='other_doc',
            field=models.CharField(blank=True, default=304251034, help_text='Chứng từ khác', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contractdesc',
            name='plate_number',
            field=models.CharField(blank=True, default=8925972774, help_text='Biển số xe', max_length=300, null=True),
        ),
    ]
